 
Running threaded PSI4 on node17 
/home/qc//psi4conda/bin/psi4
 
Working and scratch directories
/home/mdavis/f12eom_optimizer/tests/slurm
/scratch/mdavis/PSI4_2022-08-16_13:00:27.509189242
 
use -n:  to specify number of threads
use -i:  to specify input  file     (default = input.dat)
use -o:  to specify output file     (default = file.out )
 
-h or --help for more options
 
Running...
Traceback (most recent call last):
  File "/home/mdavis/f12eom_optimizer/f12eom_optimizer/f12eom_optimizer.py", line 18, in <module>
    psi4.optimize(compute_psi4_gradient)
  File "/home/qc/psi4conda/lib/python2.7/site-packages/psi4/driver/driver.py", line 1111, in optimize
    G, wfn = gradient(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)
  File "/home/qc/psi4conda/lib/python2.7/site-packages/psi4/driver/driver.py", line 729, in gradient
    E, wfn = energy(lowername, return_wfn=True, molecule=moleculeclone, **kwargs)
  File "/home/qc/psi4conda/lib/python2.7/site-packages/psi4/driver/driver.py", line 430, in energy
    return name(energy, kwargs.pop('label', 'custom function'), ptype='energy', **kwargs)
TypeError: compute_psi4_gradient() got an unexpected keyword argument 'opt_iter'
...Done
 
